os:
    - linux
    - windows

language: node_js
node_js:
    - "8"
    - "10"

services:
# https://docs.travis-ci.com/user/database-setup/

before_script:
    # - npm install -g eslint mocha eslint-plugin-haraka

script:
    - npm run lint
    - npm test

after_success:
   - npm install istanbul codecov
   - npm run cover
   - node_modules/.bin/codecov

sudo: false
