name: Tests

on: [ push ]

jobs:

  build-matrix:
    runs-on: ubuntu-latest
    outputs:
      supported: ${{ steps.set-matrix.outputs.lts }}
    steps:
    - uses: msimerson/node-lts-versions@v1.1
      id: set-matrix

  ci-test:

    runs-on: ${{ matrix.os }}
    needs: build-matrix

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        node: ${{ fromJson(needs.build-matrix.outputs.supported) }}
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      name: Node ${{ matrix.node }} on ${{ matrix.os }}
      with:
        node-version: ${{ matrix.node }}

    - run: npm install
    - run: npm test
      env:
        CI: true
