name: Tests

on: [ push ]

jobs:

  build-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.ci-test.strategy.matrix.node }}
    steps:
    - uses: msimerson/node-lts-versions@v1
    - run: npm install
    - run: node main.js

  ci-test:

    runs-on: ${{ matrix.os }}
    needs: build-matrix

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        node: ${{fromJSON(needs.build-matrix.outputs.matrix)}}
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      name: Node ${{ matrix.node }} on ${{ matrix.os }}
      with:
        node-version: ${{ matrix.node }}

    - run: npm install
    - run: npm test
      env:
        CI: true
